In [24]:
pip install psycopg2-binary sqlalchemy

Requirement already satisfied: psycopg2-binary in c:\users\dhanu\anaconda3_new\lib\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\users\dhanu\anaconda3_new\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\dhanu\anaconda3_new\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\dhanu\anaconda3_new\lib\site-packages (from sqlalchemy) (4.12.2)
Note: you may need to restart the kernel to use updated packages.

In [25]:
from sqlalchemy import create_engine
engine=create_engine(
    "postgresql://user:password@localhost:5432/flightdb")

In [26]:
import pandas as pd
df=pd.read_sql("SELECT * FROM flights",engine)
df

,id,flight_iata,airline,departure_airport,arrival_airport,flight_status,created_at
0,1,SU654,Aeroflot,Novyy,Suvarnabhumi International,active,2026-06-01 15:37:06.774239
1,2,ID6267,Batik Air,Pattimura,Hasanudin,scheduled,2026-06-01 15:37:06.778477
2,3,5X138,UPS,Shenzhen,Sydney Kingsford Smith Airport,scheduled,2026-06-01 15:37:06.782255
3,4,A31207,Aegean Airlines,Singapore Changi,Franz Josef Strauss,active,2026-06-01 15:37:06.785758
4,5,SK8000,SAS,Singapore Changi,Kastrup,active,2026-06-01 15:37:06.789506
...,...,...,...,...,...,...,...
255,256,AQ1195,9 Air,Guangzhou Baiyun International,Yingkou Lanqi Airport\r\n,scheduled,2026-06-01 16:38:03.953696
256,257,CA3115,Air China,Shanghai Pudong International,Noibai International,scheduled,2026-06-01 16:38:03.955700
257,258,TK6585,Turkish Airlines,Shanghai Pudong International,Istanbul Airport,scheduled,2026-06-01 16:38:03.957703
258,259,8K804,Exploits Valley Air Services,Singapore Changi,Soekarno-Hatta International,scheduled,2026-06-01 16:38:03.959984
259,260,3Y935,My Indo Airlines,Singapore Changi,Achmad Yani,scheduled,2026-06-01 16:38:03.962087

In [27]:
df.head()

,id,flight_iata,airline,departure_airport,arrival_airport,flight_status,created_at
0,1,SU654,Aeroflot,Novyy,Suvarnabhumi International,active,2026-06-01 15:37:06.774239
1,2,ID6267,Batik Air,Pattimura,Hasanudin,scheduled,2026-06-01 15:37:06.778477
2,3,5X138,UPS,Shenzhen,Sydney Kingsford Smith Airport,scheduled,2026-06-01 15:37:06.782255
3,4,A31207,Aegean Airlines,Singapore Changi,Franz Josef Strauss,active,2026-06-01 15:37:06.785758
4,5,SK8000,SAS,Singapore Changi,Kastrup,active,2026-06-01 15:37:06.789506

In [28]:
df.tail()

,id,flight_iata,airline,departure_airport,arrival_airport,flight_status,created_at
255,256,AQ1195,9 Air,Guangzhou Baiyun International,Yingkou Lanqi Airport\r\n,scheduled,2026-06-01 16:38:03.953696
256,257,CA3115,Air China,Shanghai Pudong International,Noibai International,scheduled,2026-06-01 16:38:03.955700
257,258,TK6585,Turkish Airlines,Shanghai Pudong International,Istanbul Airport,scheduled,2026-06-01 16:38:03.957703
258,259,8K804,Exploits Valley Air Services,Singapore Changi,Soekarno-Hatta International,scheduled,2026-06-01 16:38:03.959984
259,260,3Y935,My Indo Airlines,Singapore Changi,Achmad Yani,scheduled,2026-06-01 16:38:03.962087

In [29]:
df.describe()

               id                     created_at
count  260.000000                            260
mean   130.500000  2026-06-01 16:07:25.387984640
min      1.000000     2026-06-01 15:37:06.774239
25%     65.750000  2026-06-01 15:52:08.896362496
50%    130.500000  2026-06-01 16:07:16.751705856
75%    195.250000  2026-06-01 16:22:46.171842560
max    260.000000     2026-06-01 16:38:03.962087
std     75.199734                            NaN

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 260 non-null    int64
 1   flight_iata        250 non-null    object
 2   airline            247 non-null    object
 3   departure_airport  260 non-null    object
 4   arrival_airport    259 non-null    object
 5   flight_status      260 non-null    object
 6   created_at         260 non-null    datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(5)
memory usage: 14.3+ KB

In [31]:
df.shape

(260, 7)

In [32]:
df.size

1820

In [33]:
df.isnull().sum()

id                    0
flight_iata          10
airline              13
departure_airport     0
arrival_airport       1
flight_status         0
created_at            0
dtype: int64

In [50]:
df["year"] = df["created_at"].dt.year
df["month"] = df["created_at"].dt.month
df["day"] = df["created_at"].dt.day
df["hour"] = df["created_at"].dt.hour

df.drop("created_at", axis=1, inplace=True)

In [58]:
l_cols=["airline","departure_airport","arrival_airport","flight_status","flight_iata"]
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for l_cols1 in l_cols:
    df[l_cols1]=le.fit_transform(df[l_cols1])

In [59]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix,ConfusionMatrixDisplay
from sklearn.model_selection import train_test_split

In [60]:
X=df.drop("flight_status",axis=1)
y=df["flight_status"]

In [67]:
rfc = RandomForestClassifier(
    n_estimators=200,
    max_depth=None,
    random_state=42,
    warm_start=True,
    min_samples_split=4,
    min_samples_leaf=2
)

In [68]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [69]:
rfc.fit(X_train,y_train)

RandomForestClassifier(min_samples_leaf=2, min_samples_split=4,
                       n_estimators=200, random_state=42, warm_start=True)

In [70]:
y_pred=rfc.predict(X_test)

In [71]:
print("accuracy_score:",accuracy_score(y_test,y_pred))

accuracy_score: 1.0

In [72]:
print(X.columns)

Index(['id', 'flight_iata', 'airline', 'departure_airport', 'arrival_airport',
       'year', 'month', 'day', 'hour'],
      dtype='object')

In [73]:
print(df.duplicated().sum())

0

In [74]:
print(df["flight_status"].value_counts())

flight_status
1    235
0     25
Name: count, dtype: int64

In [75]:
from sklearn.metrics import confusion_matrix

y_pred = rfc.predict(X_test)

print(confusion_matrix(y_test, y_pred))

[[ 4  0]
 [ 0 48]]

In [76]:
print("Train:", rfc.score(X_train, y_train))
print("Test :", rfc.score(X_test, y_test))

Train: 0.9855769230769231
Test : 1.0

In [77]:
print(X.columns.tolist())

['id', 'flight_iata', 'airline', 'departure_airport', 'arrival_airport', 'year', 'month', 'day', 'hour']

In [78]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rfc,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(scores)
print(scores.mean())

[0.11538462 1.         1.         0.90384615 0.90384615]
0.7846153846153846

In [81]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

X = df.drop(["flight_status", "id"], axis=1)
y = df["flight_status"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

rfc = RandomForestClassifier(
    n_estimators=200,
    max_depth=15,
    min_samples_split=4,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
)

rfc.fit(X_train, y_train)

y_pred = rfc.predict(X_test)

print("Train Accuracy:", rfc.score(X_train, y_train))
print("Test Accuracy :", rfc.score(X_test, y_test))
print(classification_report(y_test, y_pred))

Train Accuracy: 0.9903846153846154
Test Accuracy : 1.0
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00        47

    accuracy                           1.00        52
   macro avg       1.00      1.00      1.00        52
weighted avg       1.00      1.00      1.00        52

In [82]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    rfc,
    X,
    y,
    cv=5,
    scoring="accuracy"
)

print(scores)
print("Mean Accuracy:", scores.mean())

[1.         1.         1.         0.96153846 0.90384615]
Mean Accuracy: 0.9730769230769232